name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
   push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and push Image'
            run: |
              docker build . --tag ghcr.io/midaslamb/moidc:latest
              docker push ghcr.io/midaslamb/moidc:latest

